# Generated by Django 3.1.1 on 2021-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='people',
            name='designation',
            field=models.CharField(max_length=70),
        ),
    ]
